### ISSUE TITLE
No License File

### ISSUE THREAD

**Issue by mmichie** [adamvr/MQTT-For-Twisted-Python#1]
Great piece of useful code, I would love to use it, but I want to make sure I respect your copyright :)  Is this open source?

**Comment by adamvr** [comment]
Done! Good luck with it though. This was my very first python project and it shows.

**Comment by mmichie** [comment]
Thanks, I'm planning to use this for a prototype, if I make any
improvements I'll send you a pull request :)

On Tue, May 29, 2012 at 9:53 PM, Adam Rudd <
reply@reply.github.com
